name: "Bump Version"
description: "Fetches the latest tag and increments the patch version number"
outputs:
  new_tag:
    description: "The new version tag after bumping"
    value: ${{ steps.bump.outputs.new_tag }}

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Get Latest Tag
      id: get_tag
      run: |
        # Try to get the latest tag; if none, default to 0.0.0
        latest_tag=$(git tag -l | sort -V | tail -n 1)
        latest_tag=${latest_tag:-0.0.0}
        echo "Latest tag: $latest_tag"
        echo "latest_tag=$latest_tag" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Bump Patch Version
      id: bump
      run: |
        # Retrieve the latest tag from the previous step's output
        latest="${{ steps.get_tag.outputs.latest_tag }}"
        echo "Latest tag received in bump step: $latest"
        # Split the version by '.'
        IFS='.' read -r major minor patch <<< "$latest"
        new_patch=$((patch + 1))
        new_tag="$major.$minor.$new_patch"
        echo "New tag: $new_tag"
        # Output the new tag so it can be used as an output for the composite action
        echo "new_tag=$new_tag" >> "$GITHUB_OUTPUT"
      shell: bash
